<a href="https://colab.research.google.com/github/zergswim/study/blob/AI_basic/2%EC%A1%B0_3%EC%A3%BC%EC%B0%A8_%EB%AF%B8%EC%85%98_%EC%A0%9C%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Q1
import numpy as np

arr1 = np.random.rand(5,3)
arr2 = np.random.rand(3,2)

dot = arr1 @ arr2 
#dot = arr1.dot(arr2)

print(dot, dot.shape)

[[0.4484815  0.43384555]
 [0.50010039 0.64178167]
 [0.26998801 0.3121345 ]
 [0.69545142 0.66366724]
 [0.59306623 0.65242754]] (5, 2)


In [ ]:
#Q2
arr1 = np.array([[5,7],[9,11]], float)
arr2 = np.array([[2,4],[6,8]], float)

concat1 = np.vstack((arr1, arr2))
concat2 = np.hstack((arr1, arr2))
#concat1 = np.concatenate((arr1, arr2), axis=0)
#concat2 = np.concatenate((arr1, arr2), axis=1)

print(concat1)
print(concat2)

[[ 5.  7.]
 [ 9. 11.]
 [ 2.  4.]
 [ 6.  8.]]
[[ 5.  7.  2.  4.]
 [ 9. 11.  6.  8.]]


In [ ]:
#Q3
xy = np.array([[1., 2., 3., 4., 5., 6.],
              [10., 20., 30., 40., 50., 60.]])

x_train = xy[0]
y_train = xy[1]

print(x_train, x_train.shape)
print(y_train, y_train.shape)

[1. 2. 3. 4. 5. 6.] (6,)
[10. 20. 30. 40. 50. 60.] (6,)


In [ ]:
#Q4
beta_gd = np.random.rand(1)
bais = np.random.rand(1)

print(beta_gd, bais)

[0.83914004] [0.90195064]


In [ ]:
#Q5
import numpy as np
xy = np.array([[1., 2., 3., 4., 5., 6.],
              [3., 6., 9., 12., 15., 18.]])

#-1:size를 기반으로 row 개수 산정, 1차원 행렬변환
x_train = xy[0].reshape(-1,1)
y_train = xy[1].reshape(-1,1)

beta_gd = np.random.rand(1).reshape(-1,1)
bais = np.random.rand(1)
learning_rate = 0.001

import math
def l2norm(x):
  x_norm = x * x
  x_norm = np.sum(x_norm)
  x_norm = np.sqrt(x_norm)
  return x_norm

for i in range(1000+1):
  error = y_train - (x_train @ beta_gd)
  grad = - x_train.T @ error 
  beta_gd = beta_gd - learning_rate * grad
  #여기서 bais 는 필요가 없는 것일까?
  #bais = bais - learning_rate * grad

  if i%100 == 0:
    print("Epoch ({:10d}/1000) error : {:10f} grad : {:10f} beta_gd : {:10f} bais : {:10f}".format(i, l2norm(error), l2norm(grad), l2norm(beta_gd), l2norm(bais)))

Epoch (         0/1000) error :  21.438727 grad : 204.512418 beta_gd :   0.957123 bais :   0.538997
Epoch (       100/1000) error :   0.001540 grad :   0.014693 beta_gd :   2.999853 bais :   0.538997
Epoch (       200/1000) error :   0.000000 grad :   0.000001 beta_gd :   3.000000 bais :   0.538997
Epoch (       300/1000) error :   0.000000 grad :   0.000000 beta_gd :   3.000000 bais :   0.538997
Epoch (       400/1000) error :   0.000000 grad :   0.000000 beta_gd :   3.000000 bais :   0.538997
Epoch (       500/1000) error :   0.000000 grad :   0.000000 beta_gd :   3.000000 bais :   0.538997
Epoch (       600/1000) error :   0.000000 grad :   0.000000 beta_gd :   3.000000 bais :   0.538997
Epoch (       700/1000) error :   0.000000 grad :   0.000000 beta_gd :   3.000000 bais :   0.538997
Epoch (       800/1000) error :   0.000000 grad :   0.000000 beta_gd :   3.000000 bais :   0.538997
Epoch (       900/1000) error :   0.000000 grad :   0.000000 beta_gd :   3.000000 bais :   0.538997


In [ ]:
#응용 다차원 배열 테스트..., beta_gd 를 다차원으로 하는 방법은?? , W.T * X + b = Y 형으로 고려?
import numpy as np
SIZE = 180 #다차원 크기 지정
x_train = np.random.rand(SIZE, 6)
y_train = (np.random.rand(6)*100).reshape(-1,1)

beta_gd = np.random.rand(1).reshape(-1,1)
bais = np.random.rand(1)
learning_rate = 0.001

import math
def l2norm(x):
  x_norm = x * x
  x_norm = np.sum(x_norm)
  x_norm = np.sqrt(x_norm)
  return x_norm

import random
for i in range(1000+1):
  r = random.randrange(1, SIZE)
  x_train_one = x_train[r].reshape(-1,1)

  error = y_train - (x_train_one @ beta_gd)
  grad = - x_train_one.T @ error
  beta_gd = beta_gd - learning_rate * grad
  #bais = bais - learning_rate * grad

  if i%100 == 0:
    print("Epoch ({:10d}/1000) error : {:10f} grad : {:10f} beta_gd : {:10f} bais : {:10f}".format(i, l2norm(error), l2norm(grad), l2norm(beta_gd), l2norm(bais)))

print("--NEXT--")

for i in range(10000+1):
  pred = x_train_one * beta_gd + beta_gd
  error = ((pred - y_train) ** 2).mean()

  gd_w = ((pred - y_train) * 2 * x_train_one).mean() #why?
  gd_b = ((pred - y_train) * 2).mean() #why?

  beta_gd = beta_gd - learning_rate * grad
  bais = bais - learning_rate * grad

  if i%1000 == 0:
    print("Epoch ({:10d}/1000) error : {:10f} grad_w : {:10f} grad_b : {:10f} beta_gd : {:10f} bais : {:10f}".format(i, error, gd_w, gd_b, beta_gd.item(), bais.item()))

Epoch (         0/1000) error : 167.531796 grad : 100.511503 beta_gd :   0.762243 bais :   0.069691
Epoch (       100/1000) error : 144.597632 grad : 204.425343 beta_gd :  16.280070 bais :   0.069691
Epoch (       200/1000) error : 157.946427 grad :  34.214465 beta_gd :  29.075502 bais :   0.069691
Epoch (       300/1000) error : 133.072224 grad : 101.574633 beta_gd :  39.899602 bais :   0.069691
Epoch (       400/1000) error : 130.055234 grad :  81.365680 beta_gd :  48.517568 bais :   0.069691
Epoch (       500/1000) error : 126.448427 grad :  10.691495 beta_gd :  55.583464 bais :   0.069691
Epoch (       600/1000) error : 113.646029 grad :  73.090685 beta_gd :  61.154934 bais :   0.069691
Epoch (       700/1000) error : 123.493109 grad :  32.905482 beta_gd :  65.976548 bais :   0.069691
Epoch (       800/1000) error : 109.100635 grad :  51.591457 beta_gd :  69.848787 bais :   0.069691
Epoch (       900/1000) error :  82.810715 grad :  55.137455 beta_gd :  72.875175 bais :   0.069691


In [ ]:
#강의 예제.. 테스트용
X = np.array([[1,1], [1,2], [2,2], [2,3]])
y = np.dot(X, np.array([1,2])) * 3#X @ np.array([1,2]) * 3

beta_gd = np.random.rand(2,4) #np.array([[10.1, 15.1, -6.5, 1]]) #np.random.rand(3)
X_ = np.array([np.append(x,[1]) for x in X]) #intercept 항 추가?

print(X_.shape, y, beta_gd.shape)

for t in range(5000):
  error = y - X @ beta_gd
  grad = -np.transpose(X) @ error
  beta_gd = beta_gd - 0.01 * grad

  if(t%100 == 0):
    print("{:10f}, {:10f}, {:10f}".format(l2norm(error), l2norm(grad), l2norm(beta_gd)))

(4, 3) [ 9 15 18 24] (2, 4)
 61.820229, 304.966643,   4.723791
 21.089640,   1.575384,  12.837783
 21.008270,   1.056724,  13.143576
 20.971556,   0.708821,  13.415137
 20.955016,   0.475457,  13.625380
 20.947570,   0.318924,  13.778446
 20.944218,   0.213925,  13.886350
 20.942710,   0.143495,  13.961026
 20.942032,   0.096252,  14.012133
 20.941727,   0.064563,  14.046866
 20.941589,   0.043307,  14.070365
 20.941527,   0.029049,  14.086218
 20.941500,   0.019486,  14.096893
 20.941487,   0.013070,  14.104071
 20.941482,   0.008767,  14.108894
 20.941479,   0.005881,  14.112133
 20.941478,   0.003945,  14.114307
 20.941477,   0.002646,  14.115766
 20.941477,   0.001775,  14.116745
 20.941477,   0.001191,  14.117402
 20.941477,   0.000799,  14.117843
 20.941477,   0.000536,  14.118138
 20.941477,   0.000359,  14.118337
 20.941477,   0.000241,  14.118470
 20.941477,   0.000162,  14.118559
 20.941477,   0.000108,  14.118619
 20.941477,   0.000073,  14.118659
 20.941477,   0.000049,  14