<a href="https://colab.research.google.com/github/zergswim/study/blob/AI_basic/2%EC%A1%B0_3%EC%A3%BC%EC%B0%A8_%EB%AF%B8%EC%85%98_%EC%A0%9C%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
#Q1
import numpy as np

arr1 = np.random.rand(5,3)
arr2 = np.random.rand(3,2)

dot = arr1 @ arr2 
#dot = arr1.dot(arr2)

print(dot, dot.shape)

[[0.4484815  0.43384555]
 [0.50010039 0.64178167]
 [0.26998801 0.3121345 ]
 [0.69545142 0.66366724]
 [0.59306623 0.65242754]] (5, 2)


In [24]:
#Q2
arr1 = np.array([[5,7],[9,11]], float)
arr2 = np.array([[2,4],[6,8]], float)

concat1 = np.vstack((arr1, arr2))
concat2 = np.hstack((arr1, arr2))
#concat1 = np.concatenate((arr1, arr2), axis=0)
#concat2 = np.concatenate((arr1, arr2), axis=1)

print(concat1)
print(concat2)

[[ 5.  7.]
 [ 9. 11.]
 [ 2.  4.]
 [ 6.  8.]]
[[ 5.  7.  2.  4.]
 [ 9. 11.  6.  8.]]


In [ ]:
#Q3
xy = np.array([[1., 2., 3., 4., 5., 6.],
              [10., 20., 30., 40., 50., 60.]])

x_train = xy[0]
y_train = xy[1]

print(x_train, x_train.shape)
print(y_train, y_train.shape)

[1. 2. 3. 4. 5. 6.] (6,)
[10. 20. 30. 40. 50. 60.] (6,)


In [ ]:
#Q4
beta_gd = np.random.rand(1)
bais = np.random.rand(1)

print(beta_gd, bais)

[0.83914004] [0.90195064]


In [18]:
#Q5
import numpy as np
xy = np.array([[1., 2., 3., 4., 5., 6.],
              [3., 6., 9., 12., 15., 18.]])

#-1:size를 기반으로 row 개수 산정, 1차원 행렬변환
x_train = xy[0].reshape(-1,1)
y_train = xy[1].reshape(-1,1)

x_train = np.random.rand(6,180).reshape(-1,180)
y_train = (np.random.rand(6)*10).reshape(-1,1)

#print(x_train, y_train)

beta_gd = np.random.rand(1,180)
bais = np.random.rand(1)

learning_rate = 0.01

import math
def l2norm(x):
  x_norm = x * x
  x_norm = np.sum(x_norm)
  x_norm = np.sqrt(x_norm)
  return x_norm
  #rtn = [a*a for a in arr]
  #print(rtn)
  #return math.sqrt(sum(rtn))

for i in range(1000+1):

  error = (y_train @ np.ones((1,180))) - (x_train @ beta_gd.T)
  grad = - x_train.T @ error# + bais #여기서 bais 가 왜 필요했을까?
  beta_gd = beta_gd - learning_rate * grad
  #bais = bais - learning_rate * grad

  #print(error)
  #print(l2norm(error), l2norm(grad), l2norm(beta_gd))

  if i%100 == 0:
    print("Epoch ({:10d}/1000) error : {:10f} grad : {:10f} beta_gd : {:10f} bais : {:10f}".format(i, l2norm(error), l2norm(grad), l2norm(beta_gd), l2norm(bais)))

Epoch (         0/1000) error : 1290.356612 grad : 22076.968793 beta_gd : 148.803145 bais :   0.507441
Epoch (       100/1000) error : 63566517606205819207120404348928.000000 grad : 1089316819116399000148925971693568.000000 beta_gd : 7183777048333440113640787148800.000000 bais :   0.507441
Epoch (       200/1000) error : 3222922711914822083828577112824710968123504616906675223265280.000000 grad : 55230081008224399837798041593644770475549337003813156476157952.000000 beta_gd : 364228827978331974714913582460894315298880692241857098285056.000000 bais :   0.507441
Epoch (       300/1000) error : 163407265304792409167537451898158293103102201605073125307697084830125780812692465825873920.000000 grad : 2800252226574218812676230843380167460261433670706574823077185024817633388880798578695471104.000000 beta_gd : 18466976109938394446647646971848513824734455727538632899442910587673171801522396897214464.000000 bais :   0.507441
Epoch (       400/1000) error : 828500610817517552838620444512364769912961

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:22: RuntimeWarning: overflow encountered in multiply


In [18]:
lst = [[a*0.2 for a in range(10)], [a*0.1 for a in range(10)]]
print(type(lst), lst.shape)

AttributeError: ignored